#!/bin/sh

# build script for ccaas builder
set -e

SOURCE="$1"
METADATA="$2"
OUTPUT="$3"

if [ -f "$SOURCE/code.tar.gz" ]; then
    tar -xf "$SOURCE/code.tar.gz" -C "$OUTPUT" connection.json
elif [ -f "$SOURCE/connection.json" ]; then
    cp "$SOURCE/connection.json" "$OUTPUT/connection.json"
else
    exit 1
fi

exit 0
