name: Benih Certification Network
version: "2.0.0"
caliper:
  blockchain: fabric

channels:
  - channelName: benihchannel
    contracts:
      - id: benih-certification

organizations:
  - mspid: BPSBPBenihMSP
    identities:
      certificates:
        - name: farmer1
          clientSignedCert:
            path: ./credentials/farmer1/cert.pem
          clientPrivateKey:
            path: ./credentials/farmer1/key.pem
        # appUser for all testing operations
        - name: appUser
          clientSignedCert:
            path: ./credentials/appUser/cert.pem
          clientPrivateKey:
            path: ./credentials/appUser/key.pem
    connectionProfile:
      path: ./networks/connection-bpsbp.yaml
      discover: true
