'use strict';

const { WorkloadModuleBase } = require('@hyperledger/caliper-core');
const dataset = require('./seed-batch-dataset.json');

/**
 * Workload module for createSeedBatch transaction - 100 TPS Round
 * Updated for seedBatchContractZTA chaincode:
 * - Batch ID is auto-generated by chaincode (BATCH-YYYYMMDD-NNNN)
 * - Added declaredQuantity and seedSourceDocHash parameters
 */
class CreateSeedBatchWorkload extends WorkloadModuleBase {
    constructor() {
        super();
        this.txIndex = 0;
    }

    /**
     * Initialize the workload module
     */
    async initializeWorkloadModule(workerIndex, totalWorkers, roundIndex, roundArguments, sutAdapter, sutContext) {
        await super.initializeWorkloadModule(workerIndex, totalWorkers, roundIndex, roundArguments, sutAdapter, sutContext);

        this.workerIndex = workerIndex;
        this.totalWorkers = totalWorkers;
        this.roundIndex = roundIndex;

        console.log(`[Worker ${workerIndex}] Initialized for Round ${roundIndex} (100 TPS). Current txIndex: ${this.txIndex}`);
    }

    /**
     * Submit transaction to create seed batch
     * Chaincode auto-generates batch ID, so we just provide seed data
     */
    async submitTransaction() {
        this.txIndex++;

        // Cycle through dataset for seed batch data
        const dataIndex = (this.workerIndex + ((this.txIndex - 1) * this.totalWorkers)) % dataset.length;
        const data = dataset[dataIndex];

        const request = {
            contractId: this.roundArguments.contractId,
            contractFunction: 'createSeedBatch',
            contractArguments: [
                data.variety,                          // varietyName
                data.commodity,                        // commodity
                data.harvestDate,                      // harvestDate
                data.seedSourceNumber,                 // seedSourceNumber
                data.origin,                           // origin
                data.iupbNumber,                       // iupbNumber
                data.seedClass,                        // seedClass
                data.producerUUID,                     // producerUUID
                data.seedSourceDocName,                // seedSourceDocName
                data.seedSourceIpfsCid,                // seedSourceIpfsCid
                data.declaredQuantity.toString(),      // declaredQuantity
                data.seedSourceDocHash                 // seedSourceDocHash (SHA256 64 hex)
            ],
            readOnly: false,
            invokerIdentity: 'appUser'  // Using appUser for testing
        };

        try {
            await this.sutAdapter.sendRequests(request);
        } catch (error) {
            // Ignore "already exists" errors to allow re-running tests without reset
            if (error.message && (error.message.includes('sudah ada') || error.message.includes('already exists'))) {
                // console.log(`Batch ${data.batchId} already exists, skipping...`);
                return;
            }
            throw error;
        }
    }

    /**
     * Cleanup workload module
     */
    async cleanupWorkloadModule() {
        // No cleanup needed
    }
}

/**
 * Create a new instance of the workload module
 * @return {WorkloadModuleInterface}
 */
function createWorkloadModule() {
    return new CreateSeedBatchWorkload();
}

module.exports.createWorkloadModule = createWorkloadModule;
